version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/var/www/html:cached
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
volumes:
  db_data:
  redis_data:
networks:
  laravel:
    driver: bridge
